name: Deploy common Azure resources

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Release environment
        required: true
        type: choice
        options:
          - dev
          - prod

permissions:
  contents: read
  id-token: write

jobs:
  deploy_azure_resources:
    name: Deploy Azure resources
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Deploy resources
        uses: azure/powershell@v1
        with:
          inlineScript: |
            Set-StrictMode -Version Latest
            $ErrorActionPreference = "Stop"
            $VerbosePreference = "Continue"
            $InformationPreference = "Continue"

            $deploymentParameters = @{
              ResourceGroupName = "${{ vars.AZURE_RESOURCE_GROUP_NAME }}"
              TemplateFile = Join-Path "${{ github.workspace }}" "common" "bicep" "main.bicep"
              TemplateParameterObject = @{
                logAnalyticsWorkspaceName = "${{ vars.AZURE_LOG_ANALYTICS_WORKSPACE_NAME }}"
                applicationInsightsName = "${{ vars.AZURE_APPLICATION_INSIGHTS_NAME }}"
                virtualNetworkName = "${{ vars.AZURE_VIRTUAL_NETWORK_NAME }}"
                containerAppSubnetName = "${{ vars.AZURE_CONTAINER_APPS_SUBNET_NAME }}"
                privateLinkSubnetName = "${{ vars.AZURE_PRIVATE_LINK_SUBNET_NAME }}"
                serviceBusNamespaceName = "${{ vars.AZURE_SERVICE_BUS_NAMESPACE_NAME }}"
                cosmosAccountName = "${{ vars.AZURE_COSMOS_ACCOUNT_NAME }}"
                containerRegistryName = "${{ vars.AZURE_CONTAINER_REGISTRY_NAME }}"
                containerRegistryReaderManagedIdentityName = "${{ vars.AZURE_CONTAINER_READER_MANAGED_IDENTITY_NAME }}"
                containerAppEnvironmentName = "${{ vars.AZURE_CONTAINER_APP_ENVIRONMENT_NAME }}"
              }
            }
            New-AzResourceGroupDeployment @deploymentParameters
          azPSVersion: "latest"
